### ISSUE TITLE
Enable Training/Testing Set Serialization

### ISSUE THREAD

**Issue by rhubarbwu** [UTMIST/oneshot-rs#3]
The augmented dataset must be formatted in a similar fashion to the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) so that we can use the [rust-autograd example](https://github.com/raskr/rust-autograd/tree/master/examples) (see `mnist_data.rs` and `cnn_mnist.rs`).

This might be complicated because our dataset resides in three layers of directories, so perhaps packing everything into a single object might be difficult. We may look to packing a single object per each language, or each language's character directory.

**Comment by Veyron2121** [comment]
# Possible Solution

1. Take sampled filenames from src/sample/mod.rs
2. Get image data for each file and make a 2 * (105 * 105) bit array, plus 1 for the label
3. Serialize that using gzip?...

**Comment by rhubarbwu** [comment]
Made redundant by https://github.com/UTMIST/oneshot-rs/commit/376acd626e4ceade7c54d8cc3ea7ba5ad3328810.
